language: go
#addons:
#  postgresql: "9.6"
#services:
#  - postgresql
env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.13

notifications:
email: false

script:
  - export GO111MODULE=on
  - cd ./article
