language: go
addons:
  postgresql: "9.6"
services:
  - postgresql

script: go test -v ./article/config/.  && go test -v ./article/controller/.  && go test -v ./article/model/.
#  - "cd wordcounter/"
#  -