language: go

env: GO111MODULE=on



notifications:
email: false


script:
  - cd ./wordcounter
  - go test .
  - cd ../
  - cd ./article
  - go test ./config/.
  - go test ./controller/.
  - go test ./model/.
